---
tags: [MySQL, database, spring-data,FCM,Android,Java-7,Java-8]
projects: [spring-boot,]
---

== Intent of the Application

Create an Android application which allows users to broadcast local events to other app users and recieve response.

== How to get this up and running

1)This is the server application for include::https://github.com/JNagarkar/buzzApp[]. This is the Spring-boot server and you can run it by running the
'Application.java' file.

2)Please search TODO items in the code.

3)For connecting to database, In the application.properties file in server located at src/main/resources/application.properties, Make appropriate changes
spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://localhost:3306/db_example
spring.datasource.username=springuser
spring.datasource.password=ThePassword

4)Your will have to generate your FCM and TicketMaster Keygen.
	FCM Keygen: PushNotificationHelper.java in Server (gs-accessing-mysql)
	TicketMaster API Keygen: TicketMasterAPICaller.java (gs-accessing-mysql  in main/java/app/api/)

5)Project video  include:: https://www.youtube.com/watch?v=USao-F1GXjk&t=175s[]


