package app;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

/**
 * Created by jaydatta on 3/18/17.
 */
    @Controller    // This means that this class is a Controller
    @RequestMapping(path="/crud1/") // This means URL's start with /demo (after Application path)
    public class TpController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    static final Logger logger = LogManager.getLogger(app.UserController.class.getName());

    @RequestMapping(value = "/users/tp",method= RequestMethod.POST)
    @ResponseBody
    public String createUser(@RequestBody MyUser user) {

        System.out.println("\n\n\n hitting server");




    if(user==null){
        System.out.println("hi");
    }
        try {
            System.out.println("hhhi"+user.toString());
        } catch (Exception e) {
            logger.error(e.getMessage());
            return e.getMessage();
        }

        return "mesg";
    }
}